name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_TAG: stepynin/nginx
  RELEASE_NAME: nginx
  NAMESPACE: netology

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Determine Docker tag
        id: determine-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ env.TAG }}

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Determine Docker tag
        id: determine-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Replace image tag in deployment.yaml
        run: |
          sed -i "s|image: ${{ env.IMAGE_TAG }}:.*|image: ${{ env.IMAGE_TAG }}:${{ env.TAG }}|" ./deployment.yaml
      
      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          
      - name: Authenticate to Kubernetes cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${KUBECONFIG}" > ${HOME}/.kube/config
          
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -n ${{ env.NAMESPACE }} -f ./deployment.yaml --validate=false --insecure-skip-tls-verify
